version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=redmine
      - DB_PASS=${PASSWD}
      - DB_NAME=redmine_production
    volumes:
      - /redmine_data/docker-redmine-data/postgresql_data:/var/lib/postgresql
    ports:
      - "5432:5432"


  redmine:
    image: sameersbn/redmine:3.4.2

    depends_on:
      - postgresql
    environment:
      - TZ=Asia/Taipei
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=${PASSWD}
      - DB_NAME=redmine_production
      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
#    - REDMINE_RELATIVE_URL_ROOT=
#    - REDMINE_SECRET_TOKEN=
      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15
      - REDMINE_CONCURRENT_UPLOADS=2

 #   - REDMINE_BACKUP_SCHEDULE=
 #   - REDMINE_BACKUP_EXPIRY=
 #   - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=msa.hinet.net
      - SMTP_HOST=msa.hinet.net
      - SMTP_PORT=25
#      - SMTP_USER=mailer@example.com
#      - SMTP_PASS=password
      - SMTP_STARTTLS=false
#      - SMTP_AUTHENTICATION=:login
      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30
    ports:
      - "80:80"
    volumes:
      - /redmine_data/docker-redmine-data/redmine_data:/home/redmine/data


